### ISSUE TITLE
마기카로기아 시트 관련

### ISSUE THREAD

**Issue by HHH1234-wed** [tateck-develop/roll20CustomSheet#1]
안녕하세요. 배포해주신 예쁜 시트들 정말 잘 쓰고 있습니다. 다름이 아니라 두 가지 문의 및 제보드리고자 합니다.

1.관계(앵커)란의 숫자를 조절할 수 있게 만들어 주셨는데 마기로기의 앵커란은 10개가 상한입니다. (대형판 p.43 1.13.03) 여러 세션을 지속해 성장하며 앵커란을 관리하는 것도 캐릭터 빌딩에 중요한 요소다 보니 10개로 고정되는 게 좋지 않을까 합니다.
2.이 부분은 요청사항인데, 캐릭터의 상흔 영역을 체크하거나 표시할 수 있으면 더 좋을 것 같습니다.

이번에 마기카로기아 시트도 배포해주셔서 정말 기뻤습니다. ^-^ 언제나 감사합니다!

**Comment by tateck-develop** [comment]
피드백 적용 완료 되었습니다. :)! 감사합니다!!
