### ISSUE TITLE
스트라토 샤우트 롤20 시트

### ISSUE THREAD

**Issue by fryzke** [tateck-develop/roll20CustomSheet#3]
안녕하세요.
롤 20 스트라토 샤우트 시트의 모티프 분야에 마법 특기 대신 기계가 들어가 있으며, 순서 또한 짐승과 바뀌어 있는 것을 확인했습니다.
혹시 잘못된 게 맞다면 수정 건의 드리고 싶습니다...!

**Comment by tateck-develop** [comment]
안녕하세요! 확인하였습니다. 해당 부분은 이번에 발표된 에러타 부분이네요. 에러타 업데이트를 진행하도록 하겠습니다!
말씀해 주셔서 감사합니다!

**Comment by fryzke** [comment]
개정전 자료임을 몰랐네요..!  빠른 피드백 감사합니다!
