### ISSUE TITLE
인세인 커스텀 시트 어빌리티 다이스 굴림 시 목표치가 나오지 않는 현상

### ISSUE THREAD

**Issue by Ryusul** [tateck-develop/roll20CustomSheet#4]
타텍님 안녕하세요, 다름이 아니라 배포해주신 인세인 커스텀 시트 사용 중 오류가 지속적으로 발생하는 것 같아서 혹시 해결할 수 있는지 여쭤보기 위하여 글 남기게 되었습니다!

발생하는 오류는 어빌리티의 다이스를 굴리면 목표치가 나오지 않는 오류이고, 추정하기로는 어빌리티가 일정 개수 이상 늘어나면 추가한 어빌리티 중 하나의 다이스 굴림에서 해당 현상이 발생하는 것 같아요ㅠㅠ

해당 오류를 고칠 수 있는 방법이 있을까요?

+) 항상 배포해주시는 시트 잘 쓰고 있습니다, 감사해요!

**Comment by tateck-develop** [comment]
기본적으로 출력되고 있는 어빌리티 칸 6개는 고유의 값을 가지고 있기 때문에 목표치 관련 스크립트가 작동해 목표치를 자동으로 계산해주나, 이 후 +add 를 눌러서 추가된 어빌리티 칸에 입력된 어빌리티들은 고유값을 가지고 있지 않기 때문에 (복사개체) 목표치 스크립트가 작동하지 않아 생기는 문제입니다.

해당문제를 해결하기 위해선, 기본적으로 입력할 수 있는 칸의 갯수를 늘려서 사용해야 합니다. 예시로, 장기 캠페인 중 하나인 <호그와트 캠페인 시트>의 경우엔 기본적으로 입력할 수 있는 칸의 갯수를 늘려 이와 같은 상황에 대비하도록 만들어져 있습니다.

이와 같은 오류는 롤20에 기본으로 등재되어 있는 시노비가미/인세인 시트에도 동일하게 발생하는 오류입니다.

시트의 어빌리티칸의 항목을 추가로 늘려주면서 끝에 있는 숫자 _01 / _02... 를 함께 변동하여 주시고 아래쪽의 스크립트 부분에도 동일하게 추가한 고유값의 숫자 만큼 늘려 주신다면 가능할거에요!
호그와트 캠페인 전용 시트의 어빌리티 부분과 스크립트 부분의 코드를 참고하신다면 수정하실 수 있습니다!

문의 감사드립니다 u u)!

**Comment by Ryusul** [comment]
답변 감사해요! 설명해주신대로 수정해보겠습니다~!
